### ISSUE TITLE
Automatically run (boolean on/off)?

### ISSUE THREAD

**Issue by patrickeddy** [looki/wanikanify#1]
How do I get this script to run automatically on each page? Having trouble with this. Love that you support Firefox with this though! Not yet ready to give everything to Google.

**Comment by patrickeddy** [comment]
I'm using Greasemonkey.

**Comment by looki** [comment]
Oh man, really sorry for the late response, I haven't checked github in ages.
I just pushed the latest version which has an "enable auto-run" feature. Simply click on it and set the value to 1, I hope that works

**Comment by patrickeddy** [comment]
Great! I implemented a hack to that, just a listener. But I like your implementation.

One thing though, it doesn't prompt for an api key when you select auto run if the api key is not there. Think it should alert for the api key, huh?

**Comment by looki** [comment]
That should be fixed now - it's late at night and I just threw something together but it should work.

**Comment by patrickeddy** [comment]
Looks good :)
