### ISSUE TITLE
function watch() { [native code] } instead of 見る

### ISSUE THREAD

**Issue by patrickeddy** [looki/wanikanify#2]
Instead of 見る, for 'watch', WaniKanify renders '_function () { [native code] }'_
Like, even the GitHub repo 'watch' above this new issue form is rendered as '_function () { [native code] }_' .

![screen shot 2014-08-09 at 11 59 16 ](https://cloud.githubusercontent.com/assets/4722077/3867254/585d9d32-1ff7-11e4-8c00-30e021477dfd.png)

**Comment by looki** [comment]
I can't confirm this issue but it actually happens with the "unwatch" button instead. Same problem. Trying to fix this right now.
BTW, looking at code with this script running is hilarious.

**Comment by patrickeddy** [comment]
I know, haha. It's impossible!

**Comment by looki** [comment]
Just a heads up, I still haven't figured out how to fix this; I didn't spend too much time on it either, but it's kind of a weird problem. I'm a noob at Javascript so I have no idea how values are processed etc., causing the function to be used as title 
PS you should probably just add github to the ignored sites for that script :P

**Comment by patrickeddy** [comment]
It's not just Github! It happens on YouTube, and everywhere there's the word 'watch'.

**Comment by patrickeddy** [comment]
I'll take a look at it eventually too, just insanely busy at the moment. This script helps a ton though.

**Comment by looki** [comment]
Ah, gotcha. That's good to know. I might get to fixing this soonish, but since it's just a minor annoyance I might wait until my exam phase is over next month

**Comment by notpushkin** [comment]
Hey, I know what the problem is.
![Dev Tools](http://i.imgur.com/9LqFBka.png)
And I posted a fix somewhere. Can't remember now.
**UPD:** It was on [WaniKani forum](http://www.wanikani.com/chat/api-and-third-party-apps/4386/page/2#post133730). [Quick fix](https://gist.github.com/f796f7e93dc384f7495e)

**Comment by looki** [comment]
Ah man, sorry, I totally didn't see your post! Thanks a lot! I'm gonna patch this tomorrow, it's super late right now and I should already be sleeping. Probably would have taken me a while to fix that, I always forget JavaScript has this property magic (I only use it for my very small amount of Userscripts, but I like it).
Gotta look into GM_config as well. Just TODAY I tried finding a nice library to make custom GreaseMonkey option dialogs but couldn't find anything. I intend to use it in my Kanji Highlighter script, which I want to implement some big new features in once I have time. BTW, Wanikanify was my first userscript, I had no idea registerMenuCommand even existed back then.
By  the way  NUMIX FTW! :D
