### ISSUE TITLE
Host it on greasyfork

### ISSUE THREAD

**Issue by notpushkin** [looki/wanikanify#3]
It would be really useful for users (I suppose). ~~Also, it would allow us to create instant install button on [wkindex](http://eddie.github.io/wkindex/), a WaniKani extension catalog :P~~ Uh oh, just disregard that, we can do it now as well. Just that with Greasy Fork it would be probably easier to manage updates.

**Comment by looki** [comment]
Alright. I'm actually already hosting my other 2 WK scripts there!
